# Write your MySQL query statement below
SELECT ROUND(COUNT(DISTINCT A1.PLAYER_ID)/
(SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY),2) AS fraction
FROM Activity A1
JOIN (
    SELECT PLAYER_ID, MIN(EVENT_DATE) AS EVENT_DATE
    FROM Activity
    GROUP BY PLAYER_ID
) AS A2 ON A1.PLAYER_ID=A2.PLAYER_ID
AND DATEDIFF(A1.EVENT_DATE,A2.EVENT_DATE)=1;